name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node v16 Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Static HTML Export
        run: npm run export
        
      - name: Disable Jekyl # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
        run: touch ./out/.nojekyll

      - name: Delpoy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
